language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
