language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '9'
  - '8'
script:
  - npm test
jobs:
  include:
    - stage: release
      if: tag IS present
      node_js: 'node'
      script: "echo 'Preparing to release...'"
      deploy:
        provider: npm
        on:
          tags: true
