language: node_js
node_js:
- node
- '8'
- '7'
- '6'
before_deploy:
  - "npm run build"
deploy:
  provider: npm
  email: nicolasmatthieu57@gmail.com
  api_key:
    secure: I/Ig3jgb+/Ch5EwC3d1w5WX3CkcrZH8KXJBP/pamZcQis7/KEbNKQVwLzi1e4Lx1fCXuwg/Hh/01r1nsZKZJBk2d7Dhaj8s3ZzHAkttxeTqjtYhDqhP06qDRMIFu+ECnz69x4Swro26wWIiScKlezNAV8KyznyUbiCv4gxxGkklwIJT5E0Z5vMmDtbaec/yQk4C/+JDo8p/vYS2tXBvuGrNGkVsmy+8/LqnuHbGOdvxh7ZrOEh09S2FMlArnBo9rb0ccwORVwNVyOxZDh7mR7w+l1O//N82vGy9cRlboyyznOVHe09KqFfv9FrRj81f34SzLF+1ugQw5mNyLMaEPkNEfWCBAzrkiym50HcudA2Y6cbHGHnyVp9X1KaIB7rTmbTz6pjn9fq6AzZXG9J0P+9Y5gWNTRJT9gWzPt1ELKt8l+GF+DXOpTRA3EM9jmAWTmfTYtEPWvo50WkNyliuMAPHdqYNrnI6ydADuh7+VV9DRhG5Ta56O7T2gjUjJcx2vXPf1qjLynPOeC4dl/S3rz93uV5C1kiG8fCba9aMmJSVd7p7RM0DzPYSUaFyUO2aZNpXc/AZMUEkh303U1niOu53LCk6lMDTJ2Jp0sANqA9LCQDbC6Mh6WUNUq4oEHfhFDCDU+3SUxdAjVoow8tUQGtYQQ4KaCemlkEWPerb2mbI=
  on:
    tags: true
    repo: coast-team/mute-core
  skip_cleanup: true
