language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '9'
  - '8'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - npm run test
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: 'node'
      script: npm run semantic-release
